Naive bayes classifier

In [ ]:
from sklearn.feature_extraction.text  import TfidfVectorizer
#from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB

texts = ["I love this product!", "This is terrible and disappointing.", "I feel so happy today!", "I am extremely sad."]
labels = [1, 0, 1, 0]

vector=TfidfVectorizer()
X= vector.fit_transform(texts)

model = MultinomialNB()
model.fit(X,labels)


def predict_sentiment(texts):
    Inp = vector.transform([texts])
    prediction=model.predict(Inp)

    print(Inp.toarray())
    if prediction[0]==1:
      return ("Good")
    else:
      return ("Bad")

predict_sentiment("Iam sad")


[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]]


'Bad'

In [ ]:
predict_sentiment("i like ice")

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


'Bad'

In [ ]:
predict_sentiment("Iam dissaapoint")

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


'Bad'

Bag of words

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text  import TfidfVectorizer
texts = ["I love this product!", "This is terrible and disappointing.", "I feel so happy today!", "I am extremely sad."]

vector=CountVectorizer()
vector2=TfidfVectorizer()

X=vector.fit_transform(texts)

print(vector.vocabulary_)
print(vector2.analyzer)
print("Bag of words vector:",X.toarray(),end='')

{'love': 7, 'this': 12, 'product': 8, 'is': 6, 'terrible': 11, 'and': 1, 'disappointing': 2, 'feel': 4, 'so': 10, 'happy': 5, 'today': 13, 'am': 0, 'extremely': 3, 'sad': 9}
word
Bag of words vector: [[0 0 0 0 0 0 0 1 1 0 0 0 1 0]
 [0 1 1 0 0 0 1 0 0 0 0 1 1 0]
 [0 0 0 0 1 1 0 0 0 0 1 0 0 1]
 [1 0 0 1 0 0 0 0 0 1 0 0 0 0]]

In [ ]:
import string

text = "Hello!!! How are you? NLP is @exciting, isn't it?"
clean_text = text.translate(str.maketrans('', '', string.punctuation))

print("Text without Punctuation:", clean_text)


Text without Punctuation: Hello How are you NLP is exciting isnt it


In [ ]:
import re
text = "Python & NLP are great!! But, should we keep@ hyphens - like this?"
re.sub(r'[^a-zA-Z0-9\s@-]', '', text)  # Keeps words, spaces, and hyphens

#print("Custom Cleaned Text:", clean_text)
#clean_text =

'Python  NLP are great But should we keep@ hyphens - like this'

In [ ]:
!pip install nltk

In [ ]:
import nltk
nltk.download('punkt')
nltk.download('punkt_tab')
from nltk.tokenize import word_tokenize

text = ["Hey there! NLP @2024 is awesome.", " Let's remove #special_chars & punctuations!"]
clean_tokens=[]
for sent in text:
  tokens = word_tokenize(sent)


  for word in tokens:
    if word.isalnum():
      clean_tokens.append(word)  # Keep only alphanumeric words
clean_text = " ".join(clean_tokens)


print("Cleaned Text:", clean_text)

clean_tokens

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


Cleaned Text: Hey there NLP 2024 is awesome Let remove punctuations


['Hey',
 'there',
 'NLP',
 '2024',
 'is',
 'awesome',
 'Let',
 'remove',
 'punctuations']

In [ ]:
import nltk
nltk.download('punkt')
from nltk.tokenize import word_tokenize

text = "Hey there! NLP @2024 is awesome. Let's remove #special_chars & punctuations!"
tokens = word_tokenize(text)

clean_tokens = []  # Initialize an empty list to store cleaned words

for word in tokens:
    if word.isalnum():  # Keep only alphanumeric words
        clean_tokens.append(word)

clean_text = " ".join(clean_tokens)  # Join words to form cleaned text

print("Cleaned Text:", clean_text)


Cleaned Text: Hey there NLP 2024 is awesome Let remove punctuations


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [ ]:
text = "Hey there! NLP @2024 is awesome. Let's remove #special_chars & punctuations!"
tokens=[text.split()]

for word in tokens:
    if word.isalnum():  # Keep only alphanumeric words
        clean_tokens.append(word)